### ISSUE TITLE
Authors not indexed

### ISSUE THREAD

**Issue by cpshaw99** [CRJI/theblacksea.eu#152] opened 2018-10-29 07:55 UTC

**Comment by cpshaw99** [comment] 2018-10-29 07:56
Authors not including in the search index

**Comment by nightsh** [comment] 2018-11-02 09:15
Shouldn't the search be an article search, or should it be a "global search", looking everywhere? In this case, there should be some difference in search results template between, say, authors and stories, right?

**Comment by mgax** [comment] 2018-11-02 11:57
Duplicate of https://github.com/CRJI/theblacksea.eu/issues/166

**Closed by mgax** 2018-11-02 11:57 UTC
